Repository GraciaMoulisKevin/Thovin, pull requests merged in 2021-04, with the labels that each got.

#13 Improve Application UI
  .idea/.gitignore
  .idea/Thovin.iml
  .idea/caches/build_file_checksums.ser
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules/app/Thovin.app.iml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/thovin/AccountEditorFragment.java
  app/src/main/java/com/example/thovin/AccountFragment.java
  app/src/main/java/com/example/thovin/AuthenticationActivity.java
  app/src/main/java/com/example/thovin/AuthenticationClientActivity.java
  app/src/main/java/com/example/thovin/AuthenticationDelivererActivity.java
  app/src/main/java/com/example/thovin/AuthenticationFragment.java
  app/src/main/java/com/example/thovin/CartActivity.java
  app/src/main/java/com/example/thovin/CartFragment.java
  app/src/main/java/com/example/thovin/HomeFragment.java
  app/src/main/java/com/example/thovin/MainActivity.java
  app/src/main/java/com/example/thovin/ProfilActivity.java
  app/src/main/java/com/example/thovin/ProfilEditorActivity.java
  app/src/main/res/drawable/ic_outline_shopping_bag_24.xml
  app/src/main/res/drawable/ic_round_add_24.xml
  app/src/main/res/drawable/ic_round_border_color_24.xml
  app/src/main/res/drawable/ic_round_build_24.xml
  app/src/main/res/drawable/ic_round_delete_24.xml
  app/src/main/res/drawable/ic_round_home_24.xml
  app/src/main/res/drawable/ic_round_menu_24.xml
  app/src/main/res/drawable/ic_round_person_24.xml
  app/src/main/res/drawable/ic_round_remove_24.xml
  app/src/main/res/drawable/ic_round_search_24.xml
  app/src/main/res/layout/activity_authentication.xml
  app/src/main/res/layout/activity_authentication_client.xml
  app/src/main/res/layout/activity_authentication_deliverer.xml
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profil.xml
  app/src/main/res/layout/activity_profil_editor.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_account_editor.xml
  app/src/main/res/layout/fragment_authentication.xml
  app/src/main/res/layout/fragment_authentication_client.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/menu/activity_main_menu_drawer.xml
  app/src/main/res/menu/top_app_bar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
  local.properties
Labels: documentation, enhancement

#16 User Interface improvement done (issue #11)
  app/src/main/java/com/example/thovin/AuthenticationClientFragment.java
  app/src/main/java/com/example/thovin/AuthenticationDelivererFragment.java
  app/src/main/res/layout/fragment_authentication_deliverer.xml
Labels: documentation

#28 feature/clientHomepage
  .idea/caches/build_file_checksums.ser
  app/build.gradle
  app/src/main/java/com/example/thovin/MainActivity.java
  app/src/main/java/com/example/thovin/Utility.java
  app/src/main/java/com/example/thovin/models/auth/AuthResult.java
  app/src/main/java/com/example/thovin/models/auth/LoginModel.java
  app/src/main/java/com/example/thovin/models/auth/RegisterModel.java
  app/src/main/java/com/example/thovin/models/cart/CartModel.java
  app/src/main/java/com/example/thovin/models/order/OrderModel.java
  app/src/main/java/com/example/thovin/models/payment/CreditCartModel.java
  app/src/main/java/com/example/thovin/models/restaurant/MenuModel.java
  app/src/main/java/com/example/thovin/models/restaurant/ProductModel.java
  app/src/main/java/com/example/thovin/models/user/AddressModel.java
  app/src/main/java/com/example/thovin/models/user/UserModel.java
  app/src/main/java/com/example/thovin/services/AuthServices.java
  app/src/main/java/com/example/thovin/services/CartServices.java
  app/src/main/java/com/example/thovin/services/HttpClient.java
  app/src/main/java/com/example/thovin/services/OrdersServices.java
  app/src/main/java/com/example/thovin/services/ProductsServices.java
  app/src/main/java/com/example/thovin/ui/account/AccountFragment.java
  app/src/main/java/com/example/thovin/ui/auth/AuthClientFragment.java
  app/src/main/java/com/example/thovin/ui/auth/AuthDelivererFragment.java
  app/src/main/java/com/example/thovin/ui/auth/AuthRestaurantFragment.java
  app/src/main/java/com/example/thovin/ui/auth/UserViewModel.java
  app/src/main/java/com/example/thovin/ui/auth/UserViewModelRepository.java
  app/src/main/java/com/example/thovin/ui/home/HomeClientFragment.java
  app/src/main/java/com/example/thovin/ui/home/RestaurantAdapter.java
  app/src/main/res/drawable/ic_round_markunread_mailbox_24.xml
  app/src/main/res/drawable/round_rectangle_white.xml
  app/src/main/res/drawable/spinner_bg_circle.xml
  app/src/main/res/layout/activity_client_content.xml
  app/src/main/res/layout/activity_deliverer_content.xml
  app/src/main/res/layout/activity_main_content.xml
  app/src/main/res/layout/activity_restaurant_content.xml
  app/src/main/res/layout/adapter_restaurant.xml
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/layout/fragment_auth_client.xml
  app/src/main/res/layout/fragment_auth_deliverer.xml
  app/src/main/res/layout/fragment_auth_restaurant.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_home_client.xml
  app/src/main/res/layout/progress_spinner.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#41 Deliverer Status
  .gitignore
  .idea/caches/build_file_checksums.ser
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/thovin/ui/home/DelivererStatusFragment.java
  app/src/main/res/drawable/ic_baseline_brightness_1_24.xml
  app/src/main/res/layout/fragment_deliverer_status.xml
  app/src/main/res/navigation/deliverer_navigation.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#39 remove redundancies, check password in both side
  app/src/main/java/com/example/thovin/Utility.java
  app/src/main/java/com/example/thovin/ui/auth/AuthClientFragment.java
  app/src/main/java/com/example/thovin/ui/auth/AuthDelivererFragment.java
  app/src/main/java/com/example/thovin/ui/auth/AuthRestaurantFragment.java
  app/src/main/res/values/strings.xml
Labels: bug

#42 feature/Logout
  .idea/caches/build_file_checksums.ser
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/thovin/ClientActivity.java
  app/src/main/java/com/example/thovin/MainActivity.java
  app/src/main/java/com/example/thovin/RestaurantActivity.java
  app/src/main/java/com/example/thovin/Utility.java
  app/src/main/java/com/example/thovin/ui/auth/AuthFragment.java
  app/src/main/java/com/example/thovin/ui/auth/ClientAuthFragment.java
  app/src/main/java/com/example/thovin/ui/auth/DelivererAuthFragment.java
  app/src/main/java/com/example/thovin/ui/auth/RestaurantAuthFragment.java
  app/src/main/java/com/example/thovin/ui/home/client/ClientHomeFragment.java
  app/src/main/java/com/example/thovin/ui/home/deliverer/DelivererHomeFragment.java
  app/src/main/java/com/example/thovin/ui/home/restaurant/RestaurantAdapter.java
  app/src/main/java/com/example/thovin/ui/home/restaurant/RestaurantHomeFragment.java
  app/src/main/java/com/example/thovin/ui/parameters/ClientParametersFragment.java
  app/src/main/java/com/example/thovin/ui/parameters/RestaurantParametersFragment.java
  app/src/main/java/com/example/thovin/ui/parameters/deliverer/DelivererParametersFragment.java
  app/src/main/java/com/example/thovin/ui/parameters/deliverer/DelivererStatusFragment.java
  app/src/main/res/layout/adapter_restaurant.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_client_auth.xml
  app/src/main/res/layout/fragment_client_home.xml
  app/src/main/res/layout/fragment_client_parameters.xml
  app/src/main/res/layout/fragment_deliverer_auth.xml
  app/src/main/res/layout/fragment_deliverer_home.xml
  app/src/main/res/layout/fragment_deliverer_parameters.xml
  app/src/main/res/layout/fragment_deliverer_status.xml
  app/src/main/res/layout/fragment_restaurant_auth.xml
  app/src/main/res/layout/fragment_restaurant_home.xml
  app/src/main/res/layout/fragment_restaurant_parameters.xml
  app/src/main/res/layout/logout_button.xml
  app/src/main/res/menu/client_drawer.xml
  app/src/main/res/menu/deliverer_drawer.xml
  app/src/main/res/menu/restaurant_app_top_bar.xml
  app/src/main/res/menu/restaurant_drawer.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/client_navigation.xml
  app/src/main/res/navigation/deliverer_navigation.xml
  app/src/main/res/navigation/restaurant_navigation.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
